- name: Ippudu prompt ala rayalo chudam
  hosts: linuxserver
  vars_prompt:
  - name: USERNAME
    prompt: Please enter the username
    private: false
  - name: PASSWORD
    prompt: Please enter the password
    private: True
  tasks:
  - name: Ichina tasks ni execute cheyi
    anisible.builtin.debug:
     msg: "this was the user name i have given {{USERNAME}} and Password:{{PASSWORD}}"
