- name: these are the datatypes we are using
  hosts: linuxserver
  vars:
    firstvariable: "this is an string"
    secondvariable:
      sudheer: wasteboy
      surya: worstboy
      ravi: "deniki paniki rani vadu"
    thirdvariable: True
  tasks:
  - name: Ippudu chudam
  ansible.builtin.debug:
    msg: "mundhu first string {{firstvariable}} then it will be {{secondvariable}} if it is in{{thirdvariable}}"