- name: these are the datatypes we are using
  hosts: linuxserver
  vars:
    firstvariable: "this is an string"
    list: 
    - variable
    - turkey
    - japan
    secondvariable:
      sudheer: wasteboy
      surya: worstboy
      ravi: "deniki paniki rani vadu"
    thirdvariable: True
  tasks:
  - name: Ippudu chudam
    ansible.builtin.debug:
      msg: "mundhu first string {{firstvariable}} then list {{list}} then {{secondvariable}} if it is in{{thirdvariable}}"