- name: Filterused
  hosts: linuxserver
  tasks:
    - name: filters
      ansible.builtin.debug:
        msg: "the variable is used in the run time {{ sudheer | default (' goodboy ') }}"

- name: Uppercase
  hosts: linuxserver
  vars:
    sudheer: "Have intelligence "
  tasks:
    - name: start shows in upper case
      ansible.builtin.debug:
        msg: "{{ sudheer | upper}} "

- name: Lower case
  hosts: linuxserver
  vars:
    sudheer: "HE IS LAZYBOY"
  tasks:
    - name: Now convert into capital to small
      ansible.builtin.debug:
        msg: "{{sudheer | lower}}"

- name: remove duplicates
  hosts: linuxserver
  vars:
    iconic: [ 2,22,32,44,2,34,22,56,78,90,56]
  tasks:
    - name: all to remove this duplicates
      ansible.builtin.debug:
        msg: "{{iconic | unique }} "

- name: Max and Min
  hosts: linuxserver
  vars:
    marks: [22,48,56,99,120,140,6,59,270,89]
  tasks:
    - name: maximum and minimum
      ansible.builtin.debug:
        msg: " Max is {{ marks| max }} min is {{ marks| min }}"

- name: convert dictionary or map to items or list
  hosts: linuxserver
  vars:
    bags:
      handbag: daily usuage
      wallet: money usuage
      lunchbag: food usuage
  tasks:
    - name: dict2items
      ansible.builtin.debug:
        msg: "the plane dictionary is {{bags}}"
    
    - name: convert dict2items
      ansible.builtin.debug:
        msg: "after converting {{bags | dict2items}}"

- name: convert list to dictionary
  hosts: linuxserver
  vars:
    my list:
    - {'key': 'handbag', 'value': 'daily usuage'}
    - {'key': 'wallet', 'value': 'money usuage'}
    - {'key': 'lunchbag', 'value': 'food usuage'}
  tasks:
    - name: see the list
      ansible.builtin.debug:
        msg: "let show first how it looks {{my list}}"

    - name: it is an list convert dictionary
      ansible.builtin.debug:
        msg: "{{my list | items2dict}}"


