- name: Filterused
  hosts: linuxserver
  tasks:
    - name: filters
      ansible.builtin.debug:
        msg: "the variable is used in the run time {{ sudheer | default (' goodboy ') }}"

- name: Uppercase
  hosts: linuxserver
  vars:
    sudheer: "Have intelligence "
  tasks:
    - name: start shows in upper case
      ansible.builtin.debug:
        msg: "{{ sudheer | upper}} "

- name: Lower case
  hosts: linuxserver
  vars:
    sudheer: "HE IS LAZYBOY"
  tasks:
    - name: Now convert into capital to small
      ansible.builtin.debug:
        msg: "{{sudheer | lower}}"

- name: remove duplicates
  hosts: linuxserver
  vars:
    iconic: [ 2,22,32,44,2,34,22,56,78,90,56]
  tasks:
    - name: all to remove this duplicates
      ansible.builtin.debug:
        msg: "{{iconic | unique }} "


