- name: conditions in yaml
  hosts: linuxserver
  tasks:
    - name: for conditions
      ansible.builtin.commands: useradd euros
      ignore_errors: yes

    - name: now it will print after ignoring the errors
      ansible.builtin.debug:
        msg: "chavagotaku ra"
        