- name: secondloop
  hosts: linuxserver
  become: yes
  tasks:
   - name: chudam
     ansible.builtin.dnf:
      name: " {{ item }} "
      state: latest
     loop:
     - mysql
     - nginx
     - git
