- name: another loops
  hosts: linuxserver
  tasks: 
    - name: some install some needs to be absent
      ansible.builtin.dnf:
       name: "{{ item.name }}"
       state: "{{ item.state }}"
      loop:
      - { name: 'mysql', state: 'latest'}
      - { name: 'git', state: 'absent'}
      - { name: 'nginx', state: 'absent'}

